server:
  port: ${PORT}

spring:
  application:
    name: accounts-service


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://127.0.0.1:8761}/eureka/
    registerWithEureka: true
