server:
  port: 3333

spring:
  application:
    name: web-server

info:
  description: Sample app
  url: https://github.com/sample-app

zuul:
  routes:
    google:
      path: /google/**
      url: http://www.google.com

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/
    registerWithEureka: true
