server:
  port: ${PORT:2222}

spring:
  application:
    name: accounts-service


eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/
    registerWithEureka: true
